=== yazdani/diarc-parser/smallade_w_lang/com/action/db/action.dtd
<!ELEMENT type (subtypes|(name,(desc|api|postcond|taskname|locks|subtypes|var|actspec|control)*)|execute|goalspec|funcmap)*>
<!ELEMENT subtypes (type+)>
<!ELEMENT action (name,actionopts*)>
<!ELEMENT actionopts (desc|api|postcond|taskname|locks|subtypes|var|actspec|control)>
<!ELEMENT execute (name,exec)>
<!ELEMENT goalspec (name,goal)>
<!ELEMENT funcmap (funcname,funcarg,funcval)>
<!ELEMENT var (varname,vartype,varopts?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT api (#PCDATA)>
<!ELEMENT postcond (#PCDATA)>
<!ELEMENT taskname (#PCDATA)>
<!ELEMENT locks (#PCDATA)>
<!ELEMENT varname (#PCDATA)>
<!ELEMENT vartype (#PCDATA)>
<!ELEMENT varopts (varrole|vardefault)*>
<!ELEMENT varrole (#PCDATA)>
<!ELEMENT vardefault (#PCDATA)>
<!ELEMENT actspec (#PCDATA)>
<!ELEMENT control (#PCDATA)>
<!ELEMENT exec (#PCDATA)>
<!ELEMENT goal (#PCDATA)>
<!ELEMENT funcname (#PCDATA)>
<!ELEMENT funcarg (#PCDATA)>
<!ELEMENT funcval (#PCDATA)>

=== yazdani/diarc-parser/smallade_w_lang/build/com/action/db/icarus.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE type SYSTEM "action.dtd"> 
<type>  
  <name>entity</name>
  <subtypes>
    <type>      
      <name>action</name>
      <subtypes>
        <type>          
          <name>script</name>
          <subtypes>
            <!-- Begin IcarusInterpreter -->
             <type>              
	      <!-- Loop reading messages and executing actions as requested -->
	      <name>jACT-RInterpreter</name>
		      <var>
		<varname>?agent</varname>
		<vartype>actor</vartype>
	      </var>
	      <timeout>600000000</timeout>
	      <control>while</control>
	      <actspec> true</actspec>
	      <control>do</control>
	      <actspec> sleep ?agent 100</actspec>
	      <control>endwhile</control>
            </type>
            <type>              
	      <!-- Loop reading messages and executing actions as requested -->
	      <name>IcarusInterpreter</name>
		      <var>
		<varname>?agent</varname>
		<vartype>actor</vartype>
	      </var>
	      <timeout>600000000</timeout>
	      <control>while</control>
	      <actspec> true</actspec>
	      <control>do</control>
	      <actspec> sleep ?agent 100</actspec>
	      <control>endwhile</control>
            </type>
            <!-- End IcarusInterpreter -->
            <!-- Begin jACT-RInterpreter -->
            <type>              
	      <!-- Loop reading messages and executing actions as requested -->
	      <name>jACT-RInterpreter</name>
		      <var>
		<varname>?agent</varname>
		<vartype>actor</vartype>
	      </var>
	      <timeout>600000000</timeout>
	      <control>while</control>
	      <actspec> true</actspec>
	      <control>do</control>
	      <actspec> sleep ?agent 100</actspec>
	      <control>endwhile</control>
            </type>
            <!-- End jACT-RInterpreter -->
          </subtypes>
        </type>
      </subtypes>
    </type>
  </subtypes>
</type>
